services:
  - type: web
    name: proyect
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /login
    envVars:
      - key: JDBC_DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SHOW_SQL
        value: "false"
      - key: THYMELEAF_CACHE
        value: "true"
      - key: SQL_INIT_MODE
        value: "never"
